const weatherDescription = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Drizzle (Light)",
    53: "Drizzle (Moderate)",
    55: "Drizzle (Dense)",
    56: "Freezing Drizzle (Light)",
    57: "Freezing Drizzle (Dense)",
    61: "Rain (Slight)",
    63: "Rain (Moderate)",
    65: "Rain (Heavy)",
    66: "Freezing Rain (Light)",
    67: "Freezing Rain (Heavy)",
    71: "Snow fall (Slight)",
    73: "Snow fall (Moderate)",
    75: "Snow fall (Heavy)",
    77: "Snow grains",
    81: "Rain showers (Slight)",
    82: "Rain showers (Moderate)",
    80: "Rain showers (Violent)",
    85: "Snow showers (Slight)",
    86: "Snow showers (Heavy)",
  };

  export default weatherDescription;